In [5]:
import pandas as pd
import numpy as np
import os

In [ ]:
# カレントディレクトリ確認
print(os.getcwd())

/app/src

In [11]:
df = pd.read_csv("../output/rikunabi.csv")
df.head()

,Unnamed: 0,仕事の内容,求めている人材,勤務地,給与,勤務時間,休日・休暇,待遇・福利厚生,その他
0,0,日本初のLinkedInパートナーに選ばれ、顧客のニーズに応じてダイレクトリクルーティング支...,【いずれも必須】■採用業務に携わりたい方■今までの業務の中で、自身で課題解決/業務改善/PD...,本社（東京都港区） ［転勤］無,［想定年収］370万円～460万円 ［賃金形態］月給制 ［月給］265000円～328571円,［所定労働時間］8時間0分 ［休憩］60分 ［フレックスタイム制］有［コアタイム］有 11...,完全週休2日制 ［年間休日］125日 内訳：土日祝 夏期5日 その他（GW/年末年始/慶弔...,［退職金］無［社会保険］健保 厚生年金 雇用 労災 ［寮社宅］無 ［その他制度］書籍購入...,■事業について：労働人口減少、売り手市場から採用が難しい現在、攻めの採用として注目されている...
1,1,上流から下流まで全工程に携わり、お客様の課題をデータ活用の側面から解決いたします。 実務経験...,【以下いずれか必須】 ■Python、R、SQLなどを用いたデータ分析業務の経験 ■データ分...,本社（東京都品川区） ［転勤］無,［想定年収］400万円～550万円 ［賃金形態］月給制 ［月給］253000円～,［所定労働時間］8時間0分 ［休憩］60分 ［フレックスタイム制］有［コアタイム］無,完全週休2日制 ［年間休日］125日 内訳：土日祝 夏期3日 その他（慶弔/時間年休休暇(...,［退職金］無［社会保険］健保 厚生年金 雇用 労災 ［寮社宅］無,【当社について】AMBLは、全ての仕事に「三方よし」を実践することを経営理念として大切にして...
2,2,日本初のLinkedInパートナーに選ばれ、顧客のニーズに応じてダイレクトリクルーティング支...,【いずれも必須】■採用領域の知見、経験1年以上（採用人事/人材紹介業界での営業経験など）■法...,本社（東京都港区） ［転勤］無,［想定年収］500万円～710万円 ［賃金形態］月給制 ［月給］357500円～507500円,［所定労働時間］8時間0分 ［休憩］60分 ［フレックスタイム制］有［コアタイム］有 11...,完全週休2日制 ［年間休日］125日 内訳：土日祝 夏期5日 その他（GW/年末年始/慶弔...,［退職金］無［社会保険］健保 厚生年金 雇用 労災 ［寮社宅］無 ［その他制度］書籍購入...,■事業について：労働人口減少、売り手市場から採用が難しい現在、攻めの採用として注目されている...
3,3,1日243万人が利用する交通利用データ、「e METROアプリ」の利用データ及びOsaka ...,【必須】PLのご経験 【いずれか必須】◆SQLの作成及び活用経験◆機械学習などを用いた分析及...,本社（大阪府大阪市西区） ［転勤］無,［想定年収］590万円～760万円 ［賃金形態］月給制 ［月給］330000円～440000円,［所定労働時間］8時間0分 ［休憩］60分 ［フレックスタイム制］有［コアタイム］有 10...,完全週休2日制 ［年間休日］120日 内訳：土日祝 年末年始6日 その他（（12月29日～...,［退職金］有［社会保険］健保 厚生年金 雇用 労災 ［寮社宅］無,1日約243万人が利用する大阪メトロ。交通事業を中心にマーケティング/生活支援サービスや都市...
4,4,膨大なマーケティングデータの管理・分析をお任せします。オンライン広告からセミナー申込、商談化...,【必須】■事業会社またはコンサルファーム等でのデータアナリスト/データサイエンティスト経験（...,本社（東京都港区） ［転勤］当面無,［想定年収］700万円～1200万円 ［賃金形態］月給制 ［月給］585700円～100...,［所定労働時間］8時間0分 ［休憩］60分 ［フレックスタイム制］有［コアタイム］有 11...,完全週休2日制 ［年間休日］122日 内訳：土日祝 その他（年末年始/産前産後/育児/介護...,［退職金］無［社会保険］健保 厚生年金 雇用 労災 ［寮社宅］無 ［その他制度］健康診断...,【当社について】2016年に創業したTAPPは、2026年以降に上場を目指しております。創業...